### ISSUE TITLE
packagist is pointing to non-existing commit

### ISSUE THREAD

**Issue by richard-ejem** [nette/forms#103]
https://packagist.org/packages/nette/forms#v2.3.7 is pointing to commit ba93019 , which was probably amended / rewritten, failing my travis builds, i.e. https://travis-ci.org/instante/skeleton/jobs/103573706 .
Please update packagist to point to proper commit (should be a354b3f) from tag 2.3.7.

**Comment by dg** [comment]
Oh sh*t. Testing with `preferred-install: dist` is insufficient… Fixed.
