### ISSUE TITLE
Associative arrays not handled correctly

### ISSUE THREAD

**Issue by LostKobrakai** [nette/forms#115]
I've noticed that the `Form::IS_IN` rule on select boxes is not handled correctly. I'd imagine being able to just put the same array I used to build up the select into the rule, but it's neither parsed to a json valid array nor flattened, so netteForms.js would be able to correctly validate the selectbox.

**Comment by milo** [comment]
Could you please elaborate a little bit?

**Comment by LostKobrakai** [comment]
I created a select input with the following array:
```php
$data = ['a_1' => 'Test', 'a_2' => 'Test2'];
```
Using the Form::IS_IN rule with this `$data` array as filter won't work as it's testing against it's values and not the keys. In this case `array_keys` would be enough, but if optgroups are used one does need to flatten all keys out to get all the keys to test against.

**Comment by dg** [comment]
Why do you use it?

**Comment by LostKobrakai** [comment]
I'm adding the rule, because I want to make sure nobody has altered the select options to submit an invalid value.

**Comment by xificurk** [comment]
@LostKobrakai That's already built-in feature of SelectBox control, you don't need to do that.
