### ISSUE TITLE
Why TextInput::setDisabled(...) clear an input value?

### ISSUE THREAD

**Issue by newPOPE** [nette/forms#119]
Hi,

I am little confused from [setDisabled](https://api.nette.org/2.3.10/source-Forms.Controls.BaseControl.php.html#191) method:

```php
$form->addText(...)
  ->setValue('value')->setDisabled(); // setDisabled resets a value

// vs.

$form->addText(...)
  ->setDisabled()->setValue('value'); // but now setDisabled reset a value but value is set afterwards
```

Is there any reason why `setDisabled` resets a value?

**Comment by dg** [comment]
Because it doesn't distinguish whether it is the value that came from the form submission, or when it was manually set, so it clears value in both cases.

**Comment by newPOPE** [comment]
Ok, so how can I set input to "readonly" mode. 
In 1st option it resets a value but in 2nd option set disabled and after I set a value. I just thought that it can be confused for others. Maybe not I don't know.

**Comment by dg** [comment]
It is really hard to fix this issue. But it would be nice if you add it to the documentation, if it is not there.

**Comment by newPOPE** [comment]
Ok, I'll do it.

**Comment by newPOPE** [comment]
Here it is https://github.com/nette/web-content/pull/429

**Comment by hrach** [comment]
Just few days ago I had the same problem :)
