### ISSUE TITLE
Missing setRequired(TRUE | FALSE) on field when calling addFilter

### ISSUE THREAD

**Issue by foxycode** [nette/forms#124]
This one works fine:
```php
$ram = $form->addText('ram', 'Velikost paměti (GB)');
$ram->addCondition(Form::FILLED)
    ->addFilter(function ($value) {
        return round(trim(str_replace(',', '.', $value)), 1);
    });
````

This one not:
```php
$form->addText('ram', 'Velikost paměti (GB)')
    ->addFilter(function ($value) {
        return round(trim(str_replace(',', '.', $value)), 1);
    });
```

It returns warning `Missing setRequired(TRUE | FALSE) on field 'ram' in form 'form'.`

**Comment by dg** [comment]
In exception message is everything, or not? :)

**Comment by foxycode** [comment]
@dg I get it, you implemented new warnings about missing setRequired. The thing is, I don't want this input to be required. I thought that filters are applied in any case, because I was able to call `setFilter` directly on Control. It should be able to work this way again or I wuld like to see `addFilter` removed from Control direcly, it is confusing.

**Comment by foxycode** [comment]
@dg My whole case:
```php
$ram = $form->addText('ram', 'Velikost paměti (GB)');
$ram->addCondition(Form::FILLED)
    ->addFilter(function ($value) {
        return round(trim(str_replace(',', '.', $value)), 1);
    });
$ramCondition = $ram->addConditionOn($form['brand'], Form::EQUAL, 'kvm')
    ->setRequired('Zadejte prosím velikost paměti')
    ->addRule(Form::MIN, 'Minimální velikost paměti je %s GB', 0.1);

if ($this->server) {
    $ramCondition->addRule(Form::MAX, 'Maximální velikost paměti je %s GB', $this->server->memory);
}
```

It is useless condition moreover.

**Comment by dg** [comment]
> I don't want this input to be required

So call `setRequired(FALSE)`

**Comment by foxycode** [comment]
@dg Ok, this works, thanks. Still, I wouldn't know that filter is only applied on condition without going to code.

**Comment by foxycode** [comment]
@dg Would you accept pull with:
1) Removing `setFilter` method from `TextBase` class or
2) Adding `setRequired(FALSE)` to call from `TextBase`?

**Comment by dg** [comment]
setRequired(FALSE) will be default in Forms 3.0.

**Comment by foxycode** [comment]
@dg What am I missing? This is default behavior even now, isn't it?

**Comment by dg** [comment]
No, currectly is `setRequired(FALSE)` used only in addEmail and addInteger.
