### ISSUE TITLE
Support Form::DATA_INTEGER

### ISSUE THREAD

**Issue by JanTvrdik** [nette/forms#134]
Currently Nette supports `$form->getHttpData($form::DATA_LINE, 'tagIds[]')`, which returns `string[]`. It would be nice to have built-in support for `$form->getHttpData($form::DATA_INTEGER, 'tagIds[]')` which would return `int[]`.

**Comment by dg** [comment]
It is out of scope of this low level function.

**Comment by JanTvrdik** [comment]
What? How is distinguishing between type=text and textarea in scope and distinguishing between  type=text anf type=number not in scope? Gethttpdata method is commonly used with hidden inputs which often contains some id which is often integer

**Comment by dg** [comment]
Half of form elements are DATA_TEXT, half of form elements are DATA_LINE, thats the reason to distinguishing between them. Numbers, emails, urls, date etc. are very specific cases.

**Comment by JanTvrdik** [comment]
> Numbers, emails, urls, dates etc. are very specific cases

That's where I disagree. Imho integers are common enough (especially in hidden fields) to warrant the ~four lines of code (including one empty) required to implement this.

**Comment by dg** [comment]
It is about type of input field (low level), not about type of submitted data.

**Comment by JanTvrdik** [comment]
> It is about type of input fields (low level), not about type of submitted data. 

If there was HTML element which would combine `type=hidden` & `type=number` would you accept this? 

>  Integer is very broad definition.

I would just use `trim` + `Validators::isNumericInt`
