### ISSUE TITLE
Forms: Undefined property

### ISSUE THREAD

**Issue by Pub4Game** [nette/forms#139]
Hello!

I need to create a form with a field read-only and later make it active, but get the error after submit - `Undefined property: Nette\Utils\ArrayHash::$test2`. Below I have given examples of code that I use. Form becomes active and you can select any item after `$this->redrawControl('forms')`.

### Example form:
```
public function create()
{
	$form = new Form();

	$form->addSelect('test', '', [
		'1' => 'lalala'
	])
		->setRequired('Just do it!');

	$form->addSelect('test2', '', [
		'1' => '123123'
	])
		->setDisabled(true)
		->setRequired('Just do it!');

	$form->addProtection('');

	$form->addSubmit('send', 'create');

	$form->onSuccess[] = function (Form $form, $values) {
		$form->addError($values->test2);
	};

	return $form;
}
```

**I have a script that tracks changes `test`**

```
public function handleChange($change)
{
	if ($change) {
		$this['orderForm']['test2']->setDisabled(false);
	} else {
		$this['orderForm']['test2']->setDisabled(true);
	}
	$this->redrawControl('wrapper');
	$this->redrawControl('forms');
}
```

**Comment by dg** [comment]
Please for personal support please use forum at https://forum.nette.org or gitter https://gitter.im/nette/nette

You didn't read https://github.com/nette/security/issues/19?

**Comment by Pub4Game** [comment]
There's no question. There is a problem. After I use the setDisabled() out of the field it is impossible to get information even if it is active

**Comment by dg** [comment]
Ok, sorry. 

Can you try to replace setDisabled in BaseControl to this?

```php
	/**
	 * Disables or enables control.
	 * @param  bool
	 * @return static
	 */
	public function setDisabled($value = TRUE)
	{
		if ($this->disabled = (bool) $value) {
			$this->setValue(NULL);
		} elseif (($form = $this->getForm(FALSE)) && $form->isAnchored() && $form->isSubmitted()) {
			$this->loadHttpData();
		}
		return $this;
	}
```

**Comment by Pub4Game** [comment]
Unfortunately, this did not help me. I still get this error

`Undefined property: Nette\Utils\ArrayHash::$test2`

**Comment by dg** [comment]
You must call setDisabled(FALSE) after form is submitted, not in AJAX request before.

**Comment by Pub4Game** [comment]
lol. 
I want to make a field available after selecting item in a test. 
Therefore, the user first selects the item in `test`, then I use `$this['orderForm']['test2']->setDisabled(false)->setItems($rate);`

How do I call setDisabled(false) after form is submitted? xD

**Comment by dg** [comment]
You should somehow save information that field is not disabled. In hidden field or etc. You can discuss it on forum ;)

**Comment by Pub4Game** [comment]
Okay) Thank you for such quick support!
