### ISSUE TITLE
Strict types & hidden field

### ISSUE THREAD

**Issue by lukascellar** [nette/forms#152]
- bug report? no
- feature request? yes
- version: 3.0.0

### Description
Currently value of hidden field is always casted to string, even if value is null. I would like to propose to allow null value or cast value to integer/float etc if there are defined validation rules. 

forms/src/Forms/Controls/HiddenField.php:
```
public function setValue($value)
{
	if (!is_scalar($value) && $value !== NULL && !method_exists($value, '__toString')) {
		throw new Nette\InvalidArgumentException(sprintf("Value must be scalar or NULL, %s given in field '%s'.", gettype($value), $this->name));
	}
	if (!$this->persistValue) {
		$this->value = (string) $value;
	}
	return $this;
}
```

**Comment by dg** [comment]
What about `addRule(Form::INTEGER)` on hidden field?

**Comment by lukascellar** [comment]
Works `addRule(Form::INTEGER)` with hidden input in 2.4? Tried it now, but in `onSuccess` callback value of id is still a string.
