### ISSUE TITLE
The rule argument is used both as plural form and validation rule

### ISSUE THREAD

**Issue by juradee** [nette/forms#153]
- bug report
- version: v2.4.4

### Description

Pokud  ve formuláři používán translator je argument validačního pravidla použit jako argument pro translator. Validační zpráva je nejdříve přeložena a až potom prochází nahrazováním argumentů ve zprávě. Zpráva z překladu pak neodpovídá formě množného čísla ale hodnotě parametru.  

        $form = new Form();
        $form->setTranslator($this->translator);
        $form->addPassword('password', 'Password:')
                ->setRequired('Please enter your password.')
                ->addRule(Form::MIN_LENGTH, 'Password has to have length at least %d chars.', 6);

`<input name="password" class="form-control text" id="frm-userCreateForm-form-password" required="" data-nette-rules="[{&quot;op&quot;:&quot;:filled&quot;,&quot;msg&quot;:&quot;Insert your password.&quot;},{&quot;op&quot;:&quot;:minLength&quot;,&quot;msg&quot;:&quot;2&quot;,&quot;arg&quot;:6}]" data-lfv-initialized="true" data-lfv-message-id="frm-userCreateForm-form-password_message" type="password">`

Místo požadované zprávy je pak vrácen chybný překlad pro neexistující formu množného čísla

    public static function formatMessage(Rule $rule, $withValue = TRUE) {
            $message = $rule->message;
            if ($message instanceof Nette\Utils\IHtmlString) {
                return $message;

            } elseif ($message === NULL && is_string($rule->validator) && isset(static::$messages[$rule->validator])) {
                $message = static::$messages[$rule->validator];

            } elseif ($message == NULL) { // intentionally ==
                trigger_error("Missing validation message for control '{$rule->control->getName()}'.", E_USER_WARNING);
            }

            if ($translator = $rule->control->getForm()->getTranslator()) {
        // pokud je argument číslo použije se zde jako forma množného čísla. 
                $message = $translator->translate($message, is_int($rule->arg) ? $rule->arg : NULL);
            }

            $message = preg_replace_callback('#%(name|label|value|\d+\$[ds]|[ds])#', function ($m) use ($rule, $withValue) {
                static $i = -1;
                switch ($m[1]) {
                    case 'name': return $rule->control->getName();
                    case 'label': return $rule->control instanceof Controls\BaseControl ? $rule->control->translate($rule->control->caption) : NULL;
                    case 'value': return $withValue ? $rule->control->getValue() : $m[0];
                    default:
                        $args = is_array($rule->arg) ? $rule->arg : [$rule->arg];
                        $i = (int) $m[1] ? (int) $m[1] - 1 : $i + 1;
                        return isset($args[$i]) ? ($args[$i] instanceof IControl ? ($withValue ? $args[$i]->getValue() : "%$i") : $args[$i]) : '';
                }
            }, $message);
            return $message;
        }

**Comment by dg** [comment]
I do not understand exactly what the problem is.

**Comment by juradee** [comment]
Problem is, that you cann't use translator with this construction 
->addRule(Form::MIN_LENGTH, 'Password has to have length at least %d chars.', 6);
becouse that means use 6 form of translation

**Comment by dg** [comment]
Zkus to prosím česky.

**Comment by juradee** [comment]
Na projektu používáme translator ve formuláři.  Všechny texty jsou pak přeloženy viz : $message = $translator->translate($message, is_int($rule->arg) ? $rule->arg : NULL);
Problém je, pokud použiji pravidlo 
->addRule(Form::MIN_LENGTH, 'Password has to have length at least %d chars.', 6);
pak se nejprve aplikuje překlad. Vezme se argument pravidla, což je 6 (minimální počet znaků). Toto se předá funkci pro překlad a ta pak vrací šestou formu překladu (plurál), které neexistuje. Tím pádem je v $message například prázdný řetězec. Rozhodně zde již není modifikátor  %d takže preg_replace_callback již nemůže nic najít a nastavit správná pravidla. 
 

Pokud se ve formuláři použije pravidlo, pak

**Comment by dg** [comment]
Aha. Tak si oprav translator :-)

**Comment by juradee** [comment]
Jako aby mi vracel zpět značky? V tom ale problém není. 
V 
namespace Nette\Localization; interface ITranslator je definována fce  function translate($message, $count = NULL);

což mi předepisuje, že druhý parametr co mu pošlu je "plural count" Takže mi zápis pravidla ->addRule(Form::MIN_LENGTH, 'Password has to have length at least %d chars.', 6);
vrátí 6 plurál, což úplně nechci.  Pokud bych nepoužíval plural count a všechno vracel v první formě, pak by to bylo OK, ale takhle bych musel pro tuto zprávu v překladech mít 6. plurál. 
Částečne to bude fungovat, pokud ve formuláři nebudu používat plural count a překlad místo argumentu použije rovnou null. Optimální to není a ztrácí se funkcionalita. 

$message = $translator->translate($message, NULL);


Nebo jsem něco špatně pochopil v překladech jako takových?

**Comment by dg** [comment]
Je rozdíl mezi `1 znak`, `2 znaky`, `6 znaků`. Prostě nevracej prázdný řetězec, ale vracej `% znaků`.
