### ISSUE TITLE
CsrfProtection fails when used standalone

### ISSUE THREAD

**Issue by repli2dev** [nette/forms#154]
- bug report? yes
- feature request? no
- version: 2.4.4 

### Description
When using nette/forms without Nette and already configured session, then using of CsrfProtection fails due to `Exception in Nette\Forms\Form::__toString(): Unable to set 'session.gc_maxlifetime' to value '10800' when session has been started by session.auto_start or session_start()`

Why this configuration is done when rendering form? Why this fails if it cannot be set? How is the proper way to use this functionality?

**Comment by BernhardBaumrock** [comment]
#214 this might be solved now?

**Comment by dg** [comment]
I think that it is the same bug.

**Comment by repli2dev** [comment]
Thanks guys!
