### ISSUE TITLE
Double error translation

### ISSUE THREAD

**Issue by 2bad2furious** [nette/forms#162]
- bug report? yes
- feature request? no
- version: 2.4.5

### Description
I have noticed, that erros from inputs are translated twice. When they arrive to DeafultFormRenderer::renderErrors, they are already translated. However, they are translated [again](https://github.com/nette/forms/blob/master/src/Forms/Rendering/DefaultFormRenderer.php#L232).

**Comment by dg** [comment]
Related to #145

**Comment by vlastavesely** [comment]
I prepared test to test it but no translation duplicity found on tested case. @2bad2furious could you prepare failing test?

**Comment by 2bad2furious** [comment]
I am not exactly sure how to do that. I triggered error everytime i couldnt find a translation for a message and found the bug when i couldnt get a translation for already translated message. It happened to me with backend form checking using (probably) anonymous function.
 `$form->addEmail(UserManagement::EMAIL, UserManagement::EMAIL_LABEL)
            ->setRequired(UserManagement::EMAIL_REQUIRED)
            ->addRule(function (\Nette\Forms\Controls\TextInput $email) {
                return $this->getUserManager()->isEmailUnique($email->getValue());
            }, UserManagement::EMAIL_EXISTS)`

I can try to find exactly the point, where it gets translated for the first time.

**Comment by 2bad2furious** [comment]
Found the first translation. It is called from Forms/Validator::formatMessage() at line 63.

**Comment by vlastavesely** [comment]
I think it is not a problem of the `DefaultFormRenderer` then. I am not really sure whether it can be even solved. The renderer cannot know whether a message has been translated already by other class or not.

**Comment by 2bad2furious** [comment]
I get that. But I still don't think it should be happening. It should be translated in one class or another, not both.

**Comment by vlastavesely** [comment]
I thought about it a little bit.

The only reason for the translation being in the `Validators::formatMessage()` is the `$count` parameter that is used in `translate()` method.

```php
$message = $translator->translate($message, is_int($rule->arg) ? $rule->arg : null);
```

But this seems to me to be wrong. Assume that you would like to validate whether a number is smaller than 5. Then the `$rule->arg` will be 5 and this does not have anything in common with count. Maybe I am missing something but I think it could be removed from here. But possibly, it could be a BC break.

@dg what do you think?

**Comment by dg** [comment]
It is used for validators like MIN_LENGTH, ie. `musí mít alespoň 2 znaky` vs `5 znaků`
