### ISSUE TITLE
ChoiceControls checkAllowedValues and form validation

### ISSUE THREAD

**Issue by her-ur** [nette/forms#168]
- bug report? yes
- feature request? no
- version: 2.4.6

### Description
If on select boxes checkAllowedValues === false is set and if select is required, then validation fails because getValue() on control return empty value. Is it bug or should I extend ChoiceControl and MultiChoiceControl and override getValue()?

### Steps To Reproduce
```
$selectBox = $form->addSelect('option_id');
$selectBox->setRequired()
    ->addRule(Form::FILLED, 'Select an option');
$selectBox->checkAllowedValues = false;
```

Submit form with 'option_id' that is not present in items and validation fails with error message 'Select an option' even there is an option in `$_POST` data actually.

**Comment by dg** [comment]
It checks default values, not sent values. Better name should be `checkDefaultValue`…

**Comment by dg** [comment]
Original value can be retrieved using `getRawValue()`

**Comment by freeloapp** [comment]
Yes, you are right. But problem is during validation, when in rules is getValue() always called on control and you have no chance to call getRawValue().

**Comment by her-ur** [comment]
Yes, you are right. But problem is during validation, when in rules is getValue() always called on control and you have no chance to call getRawValue().
