### ISSUE TITLE
netteForms.js: mimeType validator does not take action

### ISSUE THREAD

**Issue by dakur** [nette/forms#173]
- bug report? no
- feature request? **yes**
- version: 2.4

### Description
Even that `Nette\Forms\Helpers::exportRules()` generates rule for client-side mime type verification, it is not implemented in `netteForms.js`.

### Steps To Reproduce
1. Add control: `$form->addUpload('image')->addRule(Form::MIME_TYPE, 'jen jpg', 'image/jpeg')`
2. Render control: `<input n:name="image">`
3. Click the image input and select non-jpeg file.
4. Click form's submit button. No client-side validation is made, instead backend takes action.

**Comment by dg** [comment]
Related #172 and https://github.com/nette/forms/commit/b48d57d6e75fabfe6b3b09c4268a02cc95859618#diff-31d0814231016345eaa29e9607fc0c15
