### ISSUE TITLE
ChoiceControl::$checkAllowedValues in ChoiceControl::getValue()

### ISSUE THREAD

**Issue by holantomas** [nette/forms#177]
- bug report? yes
- feature request? N/A
- version: v2.4.7

### Description
Hi, maybe I missed something but shouldn't be used `ChoiceControl::$checkAllowedValues` in `ChoiceControl::getValue()`? If I'm using dynamic selectbox and loading items over ajax, it's returning NULL as value. So it doesn't care about value of `$checkAllowedValues`. 

I mean something like that:
```php
	/**
	 * Returns selected key.
	 * @return string|int
	 */
	public function getValue()
	{
		return array_key_exists($this->value, $this->items) || !$this->checkAllowedValues ? $this->value : null;
	}
```

**Comment by dg** [comment]
See #168
