### ISSUE TITLE
Checkboxlist in combination with a persistent parameter, never clear value.

### ISSUE THREAD

**Issue by h4kuna** [nette/forms#181]
Version: 2.4.7

### Bug Description
If you use UI\Form method="get", add checkboxlist with name list and set property $list in presenter like persistent. You never reset form. You must only remove parameters from url.

### Steps To Reproduce
- download sandbox
- Presenter _app/presenters/FormPresenter.php_
```php
<?php

namespace App\Presenters;

use Nette\Application\UI\Form;

class FormPresenter extends BasePresenter
{

	/**
	 * @persistent
	 */
	public $list = [];

	protected function createComponentForm()
	{
		$form = new Form();
		$form->setMethod($form::GET);
		$form->addCheckboxList('list', 'List', ['Foo', 'Bar', 'Doe', 'Joe']);
		$form->addSubmit('filter', 'Filter');
		return $form;
	}
}
```
- template _app/presenters/templates/Form/default.latte_
```latte
{block content}
{control form}
```
- open url [http://localhost:8000/form/](http://localhost:8000/form/) 
- click on checkbox Foo, send form
- uncheck Foo, send form and checkbox **is still checked**
In form is added hidden input
```html
<input type="hidden" name="list[0]" value="0">
```
And checkbox list is genereted like:
```html
<input type="checkbox" name="list[]" checked="" value="0">
```

If check all checkboxes and submit form moretimes, you can see many hidden inputs in form.

### Expected Behavior
Is described above

### Possible Solution
For this moment I use Nette\Forms\Form for filter form, where i don't need events, but i need to make manually a bool value.

**Comment by h4kuna** [comment]
I found bug in [DefaultFormRenderer.php:176](https://github.com/nette/forms/blob/v2.4.6/src/Forms/Rendering/DefaultFormRenderer.php#L176) because variable $name has value **list[0]** this is not contained in form components.

**Comment by dg** [comment]
What about append line  `$name = explode('[', $name, 2)[0];`

**Comment by h4kuna** [comment]
Yes, this is possible, I try `preg_replace('#\[.*#', '', $name)`, but i can not image what happen in this case.
```php
$list = $form->addContainer('list');
$list->addCheckboxList('foo', 'List', ['Foo', 'Bar', 'Doe', 'Joe']);
```
In $name variable is **list[foo][0]**.

If we want check only first level, this solution is possible. Is need check more levels?

**Comment by dg** [comment]
IMHO first level is enough.

**Comment by h4kuna** [comment]
Ok I prepare PR until the end of the week.
