### ISSUE TITLE
Multiupload rule Form::PATTERN

### ISSUE THREAD

**Issue by xjuric29** [nette/forms#190]
Version: 2.4.2

### Bug Description
Zdravím, pro akceptování jen určitých obrázků jsem začal používat pravidlo Form::PATTERN, která pro metodu addUpload funguje v pořádku. Pokud jej ale použiju na addMultiupload, vypadá to, že se na něj nebere ohled vůbec.

### Steps To Reproduce
```
protected function createComponentSomeForm() {
    $form = new Form;
    $form->addMultiUpload('img')
    ->setRequired(false)
    ->addRule(Form::PATTERN, 'Bad file type.', '.*\.(jpg|JPG|jpeg|JPEG|png|PNG)');
    $form->addSubmit('send');
    $form->onSuccess[] = [$this, 'someFormSucceeded'];
}
```

### Expected Behavior
Čekal bych, že se pattern aplikuje na všechny názvy souborů jeden po druhém a pokud alespoň jeden neodpovídá, zobrazí se chyba.

### Possible Solution
-

**Comment by h4kuna** [comment]
Hi,
better way how check image is.

```php
$form = new Form;
$form->addMultiUpload('img')
	->setRequired(FALSE)
	->addRule($form::IMAGE, 'image/jpg', 'Files must be images.');
$form->addSubmit('send');
$form->onSuccess[] = [$this, 'someFormSucceeded'];

$form->addSubmit('send');
```

And i prepare PR, for fix.

**Comment by xjuric29** [comment]
Díky za odpověď. O té druhé variantě vím, ale pokud se nepletu, akceptuje i gif a tomu jsem se chtěl vyhnout. Omlouvám se za česky psanou issue, ale s angličtinou si tolik nevěřím.

**Comment by h4kuna** [comment]
Your variant accept all file types like php, bash etc. On server bash can to have png extension and run it if you have permission.

**Comment by jzaplet** [comment]
I think it's good idea. Sometimes you have to check file name.
Examples: Users can upload file, with right mime-type, but without extensions (MAC users). In second example you have to check prefix of the file name.

**Comment by h4kuna** [comment]
@jzaplet 
It is ok, like a second check. I do that too. I send pull request and nobody response.
