### ISSUE TITLE
Latest release published to NPM is 2.4.2, current is 2.4.8

### ISSUE THREAD

**Issue by jahudka** [nette/forms#195]
Version: 2.4.3 - 2.4.8

### Bug Description
The `nette-forms` NPM package hasn't been updated in ~2 years; the last published version is 2.4.2 according to npmjs.com. Current release of `nette/forms` is 2.4.8.

### Steps To Reproduce
`npm install nette-forms`

### Expected Behavior
Version 2.4.8 is installed.

### Possible Solution
`cd Nette/Forms && sed -i -e "s/2.4.2/2.4.8/" package.json && npm publish`

**Comment by dg** [comment]
Fixed
