### ISSUE TITLE
PHP 7.3 exception/network connection lost

### ISSUE THREAD

**Issue by dlxko** [nette/forms#203]
Version: https://pastebin.com/DJuHPbaH
https://forum.nette.org/cs/31606-php-7-3-ajax-formulare-problem

### Bug Description
After updating the server to PHP 7.3 i have a problem with the forms which use the 
ajax submit requests. When I try to call the save callback on Safari, it returns 
connection lost (dump here https://pastebin.com/ZRvMMfZJ). When I try to 
send the request again it fails with the Exception here https://uloz.to/!IlAKlALY6G9C/chyba-pdf.
On Chrome it directly goes into the Exception. 

### Steps To Reproduce
Create the Ajax form
Use PHP 7.3
Send it with the params shown in the exception (request)

### Expected Behavior
Save the form without any problems

### Possible Solution
Find the solution for the exception firstly ? :)

**Comment by dg** [comment]
OPcache problem https://forum.nette.org/cs/31606-php-7-3-ajax-formulare-problem#p201526
