### ISSUE TITLE
Chyba při uploadu PHP7.1

### ISSUE THREAD

**Issue by pierotto** [nette/forms#207]
Version: 2.4.9

V UploadControl.php na řádku 83, se porovnává datový typ, objekt obsahuje string, v PHP7.1 konstanta UPLOAD_ERR_NO_FILE obsahuje int. Pokud tedy nenahrávám nic je porovnání '4' === 4. Takže neprojde formulář validací. Je používána pouze komponenta nette/forms nikoliv celé nette.

**Comment by milo** [comment]
Cannot reproduce with:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

ini_set('xdebug.overload_var_dump', 0);

$form = new Nette\Forms\Form('a');
$form->addUpload('test');
$form->addSubmit('sub');

if ($form->isSuccess()) {
    echo "OK";
}

echo $form;

echo "<xmp>";
var_dump($_FILES);
echo "</xmp>";
```
output is
```
array(1) {
    ["test"]=> array(5) {
        ["name"]=> string(0) ""
        ["type"]=> string(0) ""
        ["tmp_name"]=> string(0) ""
        ["error"]=> int(4)
        ["size"]=> int(0)
    }
}
```

**Comment by mabar** [comment]
Maybe in combination with exact version of nette/http, webserver and php? It's hard to reproduce that kind of errors without specific environment. Docker image with reproduced error would be imho perfect.

**Comment by dg** [comment]
Cannot reproduce…
