### ISSUE TITLE
Bootstrap rendering not working when rendering manually

### ISSUE THREAD

**Issue by leomat** [nette/forms#221]
If I use a custom renderer (see capture), the class I wan to add is not added when displaying the form manually

See captures to understand
![renderer](https://user-images.githubusercontent.com/227758/56366510-98cc8c00-61f3-11e9-869c-1315bff5257c.JPG)
![form_creation](https://user-images.githubusercontent.com/227758/56366506-9833f580-61f3-11e9-9602-84c20fa9689e.JPG)
![form_display](https://user-images.githubusercontent.com/227758/56366507-9833f580-61f3-11e9-886d-768861266130.JPG)
![form_result](https://user-images.githubusercontent.com/227758/56366509-98cc8c00-61f3-11e9-8df6-4942d3d02979.JPG)

**Comment by hrach** [comment]
This is intended behaviour. For manual rendering you may use github.com/nextras/forms-rendering

**Comment by leomat** [comment]
My bad.
Thanks for the reply
