### ISSUE TITLE
PHPStan callable definitions do not support custom mapped types

### ISSUE THREAD

**Issue by jiripudil** [nette/forms#224]
Version: dev-master

### Bug Description

The callable definitions introduced in #216 fail to support custom mapped types:

```php
class MappedValues {
    public string $name;
}

$form = new Nette\Forms\Form();
$form–>addText('name', 'Name');
$form->setMappedType(MappedValues::class);
$form->onSuccess[] = function (Form $form, MappedValues $values) {};
```

produces

```
Array (array<(callable(Nette\Forms\Form, array): void)|(callable(Nette\Forms\Form, Nette\Utils\ArrayHash): void)>) does not accept Closure(Nette\Forms\Form, MappedValues): void.
```

I don't know how the variance works there, but neither adding `callable(Form, object)` nor `class MappedValues extends ArrayHash` seemed to help. Perhaps @ondrejmirtes or @JanTvrdik could chime in please?

**Comment by ondrejmirtes** [comment]
Hi, there's no way to support this. Form definitions and `onSuccess` are usually in different files... We should probably revert it to `mixed`. /cc @adaamz

**Comment by adaamz** [comment]
What about array and second variant for object? mixed is too wide...
Also we should somehow fix variant with only one parameter `(Form $form): void`

**Comment by ondrejmirtes** [comment]
It will complain about dangerous calls on `object` on level 6+.

**Comment by ondrejmirtes** [comment]
> Also we should somehow fix variant with only one parameter (Form $form): void

Does not have to be fixed. It's fine to pass callable with a single parameter somewhere multiple arguments are passed.

**Comment by jiripudil** [comment]
What do you mean,by "revert it to `mixed`"? Isn't it the case that an array of `callable(Form, object)` (or `callable(Form, mixed)` for that matter) will never accept a `Closure(Form, SpecificClass)` because of LSP? The second argument type is not contravariant, so the closure is not a subtype of the callable type 🤔

**Comment by JanTvrdik** [comment]
* `callable(Form, mixed)` should accept `Closure(Form, SpecificClass)` because of gradual typing, however
* `callable(Form, object)` should not accept `Closure(Form, SpecificClass)`

**Comment by jiripudil** [comment]
> `callable(Form, mixed)` should accept

Then there must be some issue there because, apparently, it [does not](https://phpstan.org/r/76de4de4-b0ec-44b2-957c-f1e582a7d731)

**Comment by JanTvrdik** [comment]
@jiripudil Yes, that's a bug on this line https://github.com/phpstan/phpstan/blob/4415f4c5d897359433cdcbc1576d3be7bb2757ec/src/Type/CallableType.php#L70.

**Comment by ondrejmirtes** [comment]
Should be fixed: https://github.com/phpstan/phpstan/pull/2170

**Comment by dg** [comment]
What is the final consensus? `mixed` or `object`? (#223)

**Comment by jiripudil** [comment]
I believe `mixed` since `object` would not work as discussed above. I'll amend the PR

**Comment by ondrejmirtes** [comment]
FYI https://github.com/nette/forms/pull/216#issuecomment-558625917
