### ISSUE TITLE
Automaticaly use macro formContainer from Container in foreach

### ISSUE THREAD

**Issue by h4kuna** [nette/forms#227]
If i prepare form with Container by `$form->addContainer('foo')`. In template i must use
```
{foreach $form->getComponent('foo')->getComponents() as $input}
	{formContainer $input}
		<input n:name="bar">
	{/formContainer}
{/foreach}
```

Is it possilbe in compile time use macro formContainer for `foreach` and `$form->getComponent('foo')->getComponents()` automaticaly? One level indent will be less.

Result is:
```
{foreach $form->getComponent('foo')->getComponents() as $input}
	<input n:name="bar">
{/foreach}
```
I know variable `$form` can to have other name.

If you agree and describe how resolve it, i will try prepare PR.

**Comment by dg** [comment]
I don't really understand how it should work.

**Comment by h4kuna** [comment]
It's only idea, i'm not sure if is possible to implement. 

You know if you have $form and on this instance, you can call getComponents() in this moment you want use macro {formContainer }. It is only my view.

**Comment by dg** [comment]
I think it is not possible to implement and it brings a lot of magic. You can simply use `<input n:name="$input">`

**Comment by h4kuna** [comment]
ok
