### ISSUE TITLE
Forms do not submit without cookies

### ISSUE THREAD

**Issue by NoNoNo** [nette/forms#230]
Version: 3.0.2

### Bug Description

When cookies are off, forms do not submit – without any error or notice.

[`nette/application/src/Application/UI/Form.php#139`](https://github.com/nette/application/blob/master/src/Application/UI/Form.php#L139)
```php
		} elseif (!$this->getPresenter()->getHttpRequest()->isSameSite()) {
			$this->getPresenter()->detectedCsrf();
```

[`nette/http/src/Http/Request.php#242`](https://github.com/nette/http/blob/master/src/Http/Request.php#L242)
```php
	public function isSameSite(): bool
	{
		return isset($this->cookies['nette-samesite']);
	}
```

[`nette/http/src/Bridges/HttpDI/HttpExtension.php#126`](https://github.com/nette/http/blob/master/src/Bridges/HttpDI/HttpExtension.php#L126)
```php
		$code[] = Helpers::formatArgs('$response->setCookie(...?);', [['nette-samesite', '1', 0, '/', null, null, true, 'Strict']]);
```

[`nette/http/src/Http/Response.php#249`](https://github.com/nette/http/blob/master/src/Http/Response.php#L249)
```
	public function setCookie(string $name, string $value, $time, string $path = null, string $domain = null, bool $secure = null, bool $httpOnly = null, string $sameSite = null)
```

### Steps To Reproduce

1. Disable cookies in browser or clear cookies in Apache with `Header always unset Set-Cookie`.
2. Submit a form.
 
### Expected Behavior

* Process the form
* or show error

### Possible Solution

* Make `nette-samesite` cookie optional

**Comment by dg** [comment]
fixed by nette/application#f7df426a5af59daec71f43e8ba6057422d8aaaef
