### ISSUE TITLE
Inconsistent return type of `getLabel`

### ISSUE THREAD

**Issue by dakujem** [nette/forms#241]
Version: 3.*

## Problem description

For some reason, `CheckBox`, `HiddenField` and `Button` have no label by default. But the other inputs _do_ have labels.
![image](https://user-images.githubusercontent.com/443067/77317929-6a610600-6d0c-11ea-8de4-f01614aea8b5.png)

What If we did want our checkboxes to actually have a label? And render it like a label of the other elements? (For design consistency or any other reason.)
![image](https://user-images.githubusercontent.com/443067/77318487-70a3b200-6d0d-11ea-947a-3517f64bbaf4.png)

> Of course I know manual rendering could be used. But why?

Or we wanted to make it [Bootstrap-compatible](https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios) (render the input outside of `<label>` tag)?

If anyone could make Nette forms use their own implementation of Checkbox ... but we can't, since in order to use `addCheckbox` method we need to return an instance of `Nette\Forms\Control\Checkbox` and since its `getLabel` method is defined as `public function getLabel($caption = null): void` there is no way to force any other return type on it...

## Possible solution

1. drop `void` return type on `Checkbox::getLabel` method.
2. implement a mechanism to allow users to be able to select how they want the label be rendered.

In Nette 2.4 we have solved this elegantly this way (one is able to chose from 3 different styles of how `getControl` and `getLabel` return their values):
```php
    public function getControl()
    {
        $flag = $this->getLabelRenderFlag();

        // label and control wrapped together
        if ($flag === self::LABEL_NETTE_STYLE) {
            return $this->parent_getControl();
        }

        // wrap label and label separately
        if ($flag === self::LABEL_SEPARATE_WRAPPER) {
            $this->getSeparatorPrototype()->addHtml($this->getControlPart());
            $this->getSeparatorPrototype()->addHtml($this->getLabelPart());
            return $this->getSeparatorPrototype();
        }

        // only control part returned (label is rendered separately)
        return $this->getSeparatorPrototype()->addHtml($this->getControlPart());
    }

    public function getLabel($caption = null)
    {
        // label is not rendered
        if ($this->getLabelRenderFlag() !== self::LABEL_STANDALONE) {
            return parent::getLabel($caption);
        }

        // render label separately
        return $this->getLabelPart();
    }
```
I'm open to providing a PR for the above code.

---
Please also consider dropping the return type of the other methods, for consistency sake, even though it makes less sense to override labels of these methods:
- `RadioList::getLabel` 
- `HiddenField::getLabel`
- `Button::getLabel`

**Comment by dakujem** [comment]
Awesome! Thanks a lot.

How about `RadioList`'s `Html` return type?

**Comment by dg** [comment]
I think it is correct "covariant type":https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Covariant_method_return_type.

**Comment by dakujem** [comment]
Any return type is covariant to "not specified". 🤷‍♂️

Anyway, it limits extensibility and breaks consistency.

BUT hey, we are at least able to return any string (including empty strings) wrapped inside `Html` objects, so it's no biggie. 👍
Thanks for the other changes, appreciated.

**Comment by dg** [comment]
It is specified https://github.com/nette/forms/blob/fdedfc2619d75bc2f5999d03acb982557966ae56/src/Forms/Controls/BaseControl.php#L250
