### ISSUE TITLE
HTML attributes set using form renderer wrappers are ignored if a form is rendered manually

### ISSUE THREAD

**Issue by Hologos** [nette/forms#242]
Version: v3.0.3

### Bug Description
HTML attributes set using renderer wrapper array are ignored when rendering form manually. The issue was discovered using [bootstrap4 form rendering](https://github.com/nette/forms/blob/96b3e90/examples/bootstrap4-rendering.php).

### Steps To Reproduce

**DemoPresenter.php**
```php
<?php
final class HomepagePresenter extends Nette\Application\UI\Presenter
{
    protected function createComponentForm(): UI\Form
    {
        $form = new UI\Form;
        $form->addText('input', 'Input')->setRequired();
        $form->addSubmit('send', 'Send');

        $renderer = $form->getRenderer();
        $renderer->wrappers['control']['.error'] = 'is-invalid';

        return $form;
    }
}
?>
```

**default.latte**
```latte
{control form}

{form form}
    {input input}

    {input send}
{/form}
```

### Expected Behavior
Class `is-invalid` to be added to the input element as if the form is rendered using `{control form}` macro.

```html
<input type="text" name="input" class="text is-invalid" ... >
```

**Comment by dg** [comment]
This is expected behaviour. Renderer and manual rendering are two separate and different things.
