### ISSUE TITLE
ReflectionClass::hasProperty() expects parameter 1 to be string, int given

### ISSUE THREAD

**Issue by lukascellar** [nette/forms#250]
Version: 3.0.5

### Bug Description
Type error `ReflectionClass::hasProperty() expects parameter 1 to be string, int given` occurs when using form containers with name of `integer` type. 

![Snímka obrazovky 2020-06-10 o 8 40 08](https://user-images.githubusercontent.com/4516374/84235478-3240b680-aaf6-11ea-816b-3e0238ee1065.png)

### Steps To Reproduce
1. Create form container with integer name `$form->addContainer(1);`
2. Submit form

```
protected function createComponentTestForm()
{
    $form = new Form();
    $container = $form->addContainer(1);
    $container->addText('name');
    $form->addSubmit('submit', 'submit');
    $form->onSuccess[] = function (Form $form, ArrayHash $values) {};
    return $form;
}
```

### Expected Behavior
`addContainer` should accept parameters of `string|int`

<img width="347" alt="Snímka obrazovky 2020-06-10 o 10 39 37" src="https://user-images.githubusercontent.com/4516374/84246293-ba2ebc80-ab06-11ea-8cbd-6d843e04ffa6.png">

### Possible Solution
a.) Change method definition to accept only `string` name
b.) Change type of `$name` to `string` in `Nette\Forms\Container::getValues()`

**Comment by carloscz** [comment]
yeah, but patch slipped out from the 3.0.5 version and numerically named form fields are now broken :(

**Comment by dakujem** [comment]
Any release soon? Using `dev-master` for production with Nette has proven unreliable, due to constant force-pushing / history rewriting.

**Comment by dg** [comment]
The new version comes in a month and a half at the earliest. Why don't you use the previous one?

**Comment by dakujem** [comment]
Because there is a BC break between 3.0.4 and 3.0.5 (pointed out here https://github.com/nette/forms/pull/245), so I would have to downgrade my extension library on all projects as well.

**Comment by dakujem** [comment]
For anyone who stumbles upon this - it is sufficient to 
```
composer req nette/forms:"^3.0.6"
```
provided you have
```
  "minimum-stability": "dev",
  "prefer-stable": true,
```
in your `composer.json`.
`dev-master` will be installed with an option to update to stable later once the version is released.
