### ISSUE TITLE
getControl()->type reutned null of textarea field

### ISSUE THREAD

**Issue by Malin88** [nette/forms#255]
Version: v3.0.6

### Bug Description
When I set one of fields as textarea `$form->addTextArea()` then type of this fields is `null`

### Steps To Reproduce
```
$components = $form->getComponents()
foreach($components as $component) {
   var_dump($component->getControl()->type) // null if field is textarea
}
```

### Expected Behavior
return a `textarea` string

**Comment by dg** [comment]
It throws "Cannot read an undeclared property Nette\Forms\Controls\XXXX::$type".

**Comment by Malin88** [comment]
Sorry, my mistake, it was about `$form->getComponents()`. I've already corrected the code in first post

**Comment by dg** [comment]
Oh, I see. `getControl()` returns [Html element](https://doc.nette.org/en/3.0/html-elements), so there is not attribute `type`.

**Comment by Malin88** [comment]
Ok, got it, so is there any way to get all the fields and information, what is the type of field from `Form` object?

**Comment by dg** [comment]
Try this: `var_dump($component->getOption('type'))`

**Comment by Malin88** [comment]
Thank you very much! :)
