### ISSUE TITLE
macro formPrint throws exception if getControlPart is called

### ISSUE THREAD

**Issue by MartkCz** [nette/forms#258]
Version: 3.0.6

I've following checkbox:
```php
$form->addCheckbox('checkbox');
```

and simple template:
```html
<div class="col-sm-10 col-sm-offset-2">
		<div class="checkbox">
			<label for="{$val->getHtmlId()}">
				{$val->getControlPart()} {$val->caption}
			</label>
		</div>

		{include controlErrors $val}
	</div>
```
throws exception: Return value of Nette\Forms\Controls\BaseControl::getControlPart() must be an instance of Nette\Utils\Html or null, string returned

because of https://github.com/nette/forms/blob/master/src/Bridges/FormsLatte/Runtime.php#L97

possible solution:
```php
return \Nette\Utils\Html::fromText('{input ' . $this->inner->lookupPath(Form::class) . '}');
```

**Comment by dg** [comment]
I don't get it at all. How are formPrint and the template related?
