### ISSUE TITLE
SubmitButton::$onClick type causes problems for PHPStan users

### ISSUE THREAD

**Issue by ondrejmirtes** [nette/forms#265]
Version: 3.1.0

/cc @adaamz @milo @dg 

This commit https://github.com/nette/forms/commit/2fce9b9164166254babe042cd7d11214339fe3c9 changed SubmitButton::$onClick type to:

```
/** @var callable[]&((callable(Nette\Forms\Form|SubmitButton, array|object): void)|(callable(array|object): void))[]
```

Which means "pass a callable that's ready to accept either Nette\Forms\Form or SubmitButton". But users usually pass in a callable that only accepts "SubmitButton" and it looks like SubmitButton will only ever be passed as an argument: https://github.com/nette/forms/blob/2fce9b9164166254babe042cd7d11214339fe3c9/src/Forms/Controls/SubmitButton.php#L96

This change causes PHPStan to report this error on valid code:

```
Array (array<callable(Nette\Forms\Controls\SubmitButton|Nette\Forms\Form, array|object): void>) does not accept Closure(Nette\Forms\Controls\SubmitButton, array): void.
```

Is my train of thought correct? Or should user's callables be ready to accept Form instance in some cases too?

**Comment by dg** [comment]
It works in such a way that, depending on the type of hints, it passes either a button or a form (or neither). How to write annotation?

**Comment by ondrejmirtes** [comment]
Looks like this could work: https://phpstan.org/r/1f32ff3f-5bdf-4fb2-a64a-7e3eff3025f8

```php
/** @var array<callable(Form): void|callable(Button): void> */
public $onClick = [];
```
