### ISSUE TITLE
Toggle ignoring value set by javascript

### ISSUE THREAD

**Issue by aleswita** [nette/forms#267]
Version: ^3.0

### Bug Description
If you set form value by Javascript, NetteForms.js ignoring them and do not toggling.

### Steps To Reproduce
```php
<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette\Application\UI\Form;

final class HomepagePresenter extends BasePresenter
{

	protected function createComponentForm()
	{
		$form = new Form();

		$form->addSelect('select', 'Select', [0, 1])
			->setPrompt('---')
			->addCondition(Form::EQUAL, 1)
				->toggle('frm-form-hidden')
			->endCondition();

		$form->addText('hidden', 'Hidden');

		$form->addButton('set', 'Set value "1"')
			->setHtmlId('set');

		return $form;
	}

}
```

```html
{layout none}
{control form}

<script src='https://nette.github.io/resources/js/3/netteForms.min.js'></script>
<script>
	document.addEventListener('DOMContentLoaded', function () {
		let button = document.getElementById('set');

		button.addEventListener('click', function () {
			let selectControl = document.getElementById('frm-form-select');
			selectControl.value = '1';
		});
	});
</script>
```

**Comment by dg** [comment]
call `Nette.toggleForm(form)`

**Comment by aleswita** [comment]
Yes, this is the possible solution, but may be some JS libraries can some trubles and can not be do this, without edit them.
We found this issue, when we migrating from Nette 2.4, but if it is not a bug, but feature, you can close this issue.

**Comment by dg** [comment]
This couldn't work in Nette 2.4 either, because if a form value is updated using JavaScript, the onchange event handler is not fired.

If you find a way to detect a value change, I'll be happy to add it to netteForms.js.

**Comment by mskocik** [comment]
@aleswita you need to manually trigger change event after you set value programatically.

```js
selectControl.value = '1';
selectControl.dispatchEvent(new Event('change'));  // or fireEvent in older IE
```
