### ISSUE TITLE
netteForms.js on Android does not correctly focus required inputs

### ISSUE THREAD

**Issue by valekj** [nette/forms#275]
Version: 3.1

### Bug Description
If you forget to fill a required input on Android, said input is not correctly focused afterwards (no css is applied) and you can't see what you are typing.
Happens on Android 10 and 11 (Chrome), works correctly on iOS and desktop. 
If you comment out netteForms.js and keep browser validation, it works as expected even on Android.

### Steps To Reproduce
Open a form that uses netteForms.js (for example https://nette.org/cs/sign-in).
Don't fill any input and submit the form.
Javascript warning pops up informing you about missing inputs.
Click ok.
Start typing.

### Expected Behavior
Required input should be focused, css should be applied and when you start typing, you should see the letters.

**Comment by dg** [comment]
This is a Chrome issue that also affects Windows. The reason is that `alert()` loses focus.

**Comment by dg** [comment]
@valekj what returns `console.log(navigator.userAgentData)` in affected browsers?

**Comment by valekj** [comment]
Hi, sorry for the delay.

Here are the console logs from android phone (s10e, android 11, chrome 92.0.4515.159):

console.log(navigator.userAgentData):
returns an object, however when I try to convert it to JSON, I just get an empty object, so here is a screenshot:

![consolelog](https://user-images.githubusercontent.com/51269838/130417189-dd95adc7-a3d8-485c-9ab3-9d2500f36a08.PNG)

console.log(!!HTMLDialogElement.prototype.showModal):
returns "true"

Chrome (92.0.4515.159) on Windows 10 does not seem to be affected on my end.

**Comment by dg** [comment]
Can you test that this netteForms.js works properly on Android? 
https://github.com/nette/forms/tree/master/src/assets

**Comment by valekj** [comment]
It focuses the input correctly now, however the dialog looks a bit weird:

![scrshot](https://user-images.githubusercontent.com/51269838/130589899-6628d1bd-8895-4500-a9d1-e50b2a30a263.png)

Also, would it be possible to target mobile Brave as well? Unfortunately it does not have any identification in Brands property.

![brave](https://user-images.githubusercontent.com/51269838/130590056-95e60721-b762-4593-9f2a-fcdaebdcde4c.PNG)

**Comment by dg** [comment]
I can target all mobile Chromium browsers.

Unfortunately I don't have Android and I don't know how to fix the design. Can you give it a try?

**Comment by valekj** [comment]
It's nothing fancy, but what about this:

![centereddialog](https://user-images.githubusercontent.com/51269838/130606230-129fe9fe-f4d0-4e28-8a71-ca9346a59698.png)

`style.innerText = '.netteFormsModal { text-align: center; margin: auto; width: 80%; border: 1px solid #000; padding: 1rem; } .netteFormsModal button { padding: .1em 2em }';`

**Comment by dg** [comment]
In the meantime, please add the style to your CSS file and we will tweak the resulting style over time.

**Comment by valekj** [comment]
thank you!
