### ISSUE TITLE
FormPrint macro

### ISSUE THREAD

**Issue by slavista** [nette/forms#281]
Should be here called function renderBluePrint directly or should be renamed macro to bluePrint?

https://github.com/nette/forms/blob/43bc5b41eca4b2cd49838138f064089ba7e18db3/src/Bridges/FormsLatte/FormMacros.php#L311

**Comment by slavista** [comment]
Later I have found that macro "bluePrint" works. So, is it only change missed in documentation?

**Comment by dg** [comment]
It is bug d6943593b47a94c3f54d19d24ceece3f679b62a7
