### ISSUE TITLE
setValue() as well as setDefaultValue() don't set the value and the field shows error states instead

### ISSUE THREAD

**Issue by thekayshawn** [nette/forms#314]
Version: 3.1

### Bug Description
While using Nette Forms within the framework in a presenter, setValue() nor setDefaultValue() set the value of a field and instead render the errors for that field due to the required condition.

### Steps To Reproduce
Simply create an app and create a form and try setting the default value and rendering the field using either <input n:name> or {input name}, neither does the value auto-render nor can it be seen with getValue().

### Expected Behavior
setValue() should set a value and setDefaultValue() should set a default value.

**Comment by thekayshawn** [comment]
Man, don't you hate it when things auto-resolve without you doing anything? After wasting 2 days trying to find a solution, the base setValue and setDefaultValue functions now work out of the box, not saying I hate SWE but I kinda do.

**Comment by dakorpar** [comment]
What we have as a problem was some super wierd bug, I'd say maybe even a PHP related that could be same that you hitted maybe...
Looks like developers that uses windows are affected when running locally. When rendering form

> <input type="hidden" name="_do" value="form-submit">
is missing just before closing form tag (</form>). On version 3.1.11 all works fine, but on 3.1.12 form is never submitted. onBeforeRender on form never even gets submitted.

Simple login form and only when rendered with <form n:name="form">
works fine when rendered as {control form}
Another interesting thing is that after you login once with {control form} <form n:name="form">... manual rendering works fine, completelly insane... Two developers in my team were affected...

@dg did you hear something about that?
