### ISSUE TITLE
ChoiceControl::getRawValue(): Return value must be of type string|int, null returned

### ISSUE THREAD

**Issue by forgie1** [nette/forms#316]
Version: 3.2.0

### Bug Description
`BaseControl::$value` may be null, so `ChoiceControl::getRawValue()` should return also `null`.
`SelectBox::$value` may be null if SelectBox was disabled (e.g. conditionally).

```
$form = new Nette\Application\UI\Form();
$form->addSelect('xyz', 'Xyz', ['X' =>'x', 'Y' => 'y'])->setDisabled();
$form->onSuccess[] = function (Nette\Application\UI\Form $form) {
	$form['xyz']->getRawValue();
};
```

**Comment by dg** [comment]
fixed 9b82572de3fb91abde3adf609ad025d918822ddd
