### ISSUE TITLE
Validation of MimeType rule fails when FileControl->getContentType returns null

### ISSUE THREAD

**Issue by juniwalk** [nette/forms#317]
Version: v3.1.15 (and newer)

### Bug Description
Validation of MimeType rule fails when `FileControl->getContentType` returns null because it is piped through `strtolower` which expects string.

### Steps To Reproduce
Null from `FileControl->getContentType` is returned probably only if the file upload fails.

### Expected Behavior
Only string should be sent to `strtolower` function.

### Possible Solution
`$type = strtolower($file->getContentType() ?? '');`

Ref: https://github.com/nepada/file-upload-control/issues/148

**Comment by dg** [comment]
Fixed a0949bc85e7a0659ed1bbbbececd2ccca374cc3c
