### ISSUE TITLE
src/assets/netteForms.js broken in 3.2-dev

### ISSUE THREAD

**Issue by forgie1** [nette/forms#319]
Version: 3.2-dev

### Bug Description
this commit:
https://github.com/nette/forms/commit/890cebc41679b32faf66f9cc9b13ce2dbe5d8da1

this row: https://github.com/nette/forms/commit/890cebc41679b32faf66f9cc9b13ce2dbe5d8da1#r139015160

results in: `Uncaught ReferenceError: value is not defined`

**Comment by dg** [comment]
fixed
