### ISSUE TITLE
Number inputs format shouldn't be always validated

### ISSUE THREAD

**Issue by zipper** [nette/forms#328]
Version: 3.2.2

### Bug Description
When the input type number is used, it is always validated for the correct number format, even if it is not required (e.g. the input is only required if a checkbox is checked). This cannot be changed by conditional validation due to the current implementation in the `Nette.validateForm` method.

### Steps To Reproduce
```php
$form = new Form();

$checkbox = $form->addCheckbox('checkbox', 'Need a number?');

$form->addInteger('number1', 'Number')
	->addConditionOn($checkbox, Form::Equal, true)
		->setRequired();

$form->addText('number2', 'Number')
	->setHtmlType('number')
	->addConditionOn($checkbox, Form::Equal, true)
		->setRequired()
		->addRule(Form::INTEGER, 'Need a number');
```

When you input non-numerical text `foo` (e.g. in Firefox) into the inputs, the form cannot be submitted because of JS validation and `Nette.invalidNumberMessage` is shown even with unchecked checkbox. That is because number inputs are validated in `Nette.validateForm` regardless of rules set in PHP. https://github.com/nette/forms/blob/337f707ece262e9a159b14ca985c3f5c9d7054cd/src/assets/netteForms.js#L225-L231

In real life, I have the number input inside toggled container, therefore the validation message is not even visible. Only workaround I know is to disable the input with toggling, but that would require some custom JS.

### Expected Behavior
At least for `number2', the number format should not be validated unless the checkbox is actually checked. The rule explicitly says that the number is only required if the checkbox is checked. If it is unchecked, the input is ignored.

**Comment by MartinMystikJonas** [comment]
IMHO expected behaviour is to warn user that entered value is invalid instead of silently ignoring it just because it is not required. If user entered value it is expected he wanted this value to be used.

**Comment by zipper** [comment]
In the first case (`number1`)? Probably yes. But in the second case (`number2`) the validation explicitly says "do not validate unless checkbox is checked".

The real use case we have is some radio list with options, one of which is `custom`. Then the number is only used if the `custom` is selected. Otherwise the value is discarded in PHP. It doesn't make sense to validate the input in this case, nor to show the message to the user - the input is hidden for a reason, as the user chose another option from the radio list. Warning the user in this case means that the user has to take some action (clear or correct the input) even though its value won't be used.

**Comment by dg** [comment]
It works fine for me, if the checkbox is not checked, the number is not validated.

**Comment by zipper** [comment]
@dg You are right, the definition of the input in the example was wrong. I have changed the example and added the ->setHtmlType('number'). We actually want this type to be set and this is what causes the validation to always trigger. Sorry for the confusion.

There is actually probably no difference between `->addInteger(...)` and `->addText(...)->setHtmlType('number')`, is it?

**Comment by zipper** [comment]
I'm not sure if this should have been closed. I have made a mistake in the issue description (missing `setHtmlType`) and then the issue is as stated - when the html type is number, the input is always validated no matter what is set in PHP.

**Comment by dg** [comment]
As @MartinMystikJonas wrote, silently ignoring user input is not a good idea. 

The solution to your use case is to mark input as disabled with javascript when it is not needed.

**Comment by dg** [comment]
@zipper your request is in direct opposition to this #289

The question is whether the HTML attribute should cause validation. The fact is that no other attributes do this, so it makes sense to revert the original patch.

**Comment by dg** [comment]
In the end, I decided to keep the current behavior. Some discussion on this in Czech https://forum.nette.org/cs/36508-netteforms-a-moralni-dilema#p226926
