### ISSUE TITLE
Nested optgroups in SelectBox

### ISSUE THREAD

**Issue by castamir** [nette/forms#56]
Is there any reason, why it is not possible to create nested optgroups (3 or more levels) in SelectBox to get something like this: http://jsfiddle.net/Tb5Rc/5/ ?

**Comment by JanTvrdik** [comment]
This AFAIK an HTML restriction.

**Comment by fprochazka** [comment]
@castamir I see only two levels in your example

**Comment by dg** [comment]
http://www.w3.org/TR/html-markup/optgroup.html Permitted contents: Zero or more option elements
