### ISSUE TITLE
netteForms.js: common js, amd

### ISSUE THREAD

**Issue by sakren** [nette/forms#69]
Since nette-forms is registered in bower repository, it would be really greate if netteForms.js could work with common js or amd environments.

Eg. I'm using [browserify](https://github.com/substack/node-browserify) with [gulp](http://gulpjs.com/) to build my js files. But it's little bit difficult with nette forms, because I have to use something like [browserify-shim](https://github.com/thlorenz/browserify-shim) to actually simulate wanted behavior.

**Prons:**
* In common js or amd environment, Nette object will not be in global object
* Easy to use in these environments
* Nette is trying to encourage everyone to not use global services like old `Environment`, so this is just another step :wink: 

**Cons:**
* Pull request will be for whole file, because all code needs to be wrapped in function

Good example is at [nprogress](https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L4-L14) package.

**Edit** 

So even browserify-shim doesn't work

**Comment by JanTvrdik** [comment]
netteForms.js must be able to work without common js or amd environment

**Comment by vojtech-dobes** [comment]
common js / amd compatibility should be achievable without dependency on anything, I think.

**Comment by sakren** [comment]
@JanTvrdik I know and that is why I send link to nprogress, which works great in each environment and without any dependency.

Actually I had to (temporary) create custom transform function for browserify which will wrap netteForms.js into function like that:

```js
(function() {
    var Nette = Nette || {};

    // ...

    module.exports = Nette;
});
```

**Comment by sakren** [comment]
The only thing I would do differently from nprogress is line [14](https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L14), where I would use `window` instead of `this`. Thats because for example browserify wraps each module (file) in another function with different scope

**Comment by sakren** [comment]
Thank you sir

Dne so, 14. 3. 2015 17:53 uživatel David Grudl <notifications@github.com>
napsal:
