### ISSUE TITLE
Proposal: Severity types for addError

### ISSUE THREAD

**Issue by juniwalk** [nette/forms#70]
I'd like to have ability to send severity type with the addError() which would be added as a class to the item.

Real world scenario would be forms rendered with bootstrap and displaying messages in alert, if I want to show just a warning alert, there is no way to do that natively using the Forms component.

Best way would be to rethink whole error system and use 'messages' instead.
```php
$form->addMessage('This is my warning.','warning');
$email->addMessage('This email is invalid!','error');
```
To keep BC you could add alias to addError like this:
```php
public function addError($msg)
{
    $this->addMessage($msg,'error');
}
```

Now of course this is just thinking out loud, having severity types for errors would be just enough.

**Comment by Unlink** [comment]
I don't understand your use case, why you need sometimes send warning and sometimes error? What is the difference between error and warning, in both cases is form invalid or how is it?

**Comment by juniwalk** [comment]
Hi, use case could be for example sign up form, if user exists I can send message on the username input with bootstrap warning color. It's matter of choice of how to handle my forms.

**Comment by JanTvrdik** [comment]
I don't get. If the username is already taken, it should be error, not a warning.

**Comment by juniwalk** [comment]
Alright bad example. Look - all I would like is to have same flashMessages implemented for forms too. It would add to consistency and give use more power over how we handle our forms.

**Comment by Unlink** [comment]
Yes, but i don't think that there is a reason, when you need something else than error in forms.
Field is valid or not. That's something different like a flash messages, their purpose is notify user about something (success, fail, info...) but in form, we need to show only validation errors.
I can't imagine use case, when is needed something else than error.

**Comment by juniwalk** [comment]
I see, well if giving us a choice is not good enough then I don't have anything else to say.

**Comment by Majkl578** [comment]
This sounds like a valid use case for client-side code (e.g. *password is not strong enough* as a warning), but I don't see any benefit in server-side validation...

**Comment by juniwalk** [comment]
Frankly I have no idea how client-side works, I am not that into javascript.

**Comment by jtojnar** [comment]
This would be nice to have. Currently, I am building custom `Rules` instance and attaching it to a `data-form-warning-rules` attribute:

https://github.com/jtojnar/entries/commit/601b203f632bfc780457078ea4afb2224e8dc8a8#diff-4078d83a9a0ef325c67991359ddfe536R73

Then I handle it in JavaScript:

https://github.com/jtojnar/entries/commit/601b203f632bfc780457078ea4afb2224e8dc8a8#diff-20ca0a4947ea7c1006cda82eca50397c
