### ISSUE TITLE
Client-side validation of filled radiolist does not work in IE9

### ISSUE THREAD

**Issue by ondrejmirtes** [nette/forms#73]
It still shows an alert even when a radio button is selected while submitting the form.

The issue is reproduced in [this commit](https://github.com/ondrejmirtes/nette-sandbox/commit/e8c9bf693307c31cb5ad8a6b83b4d86cb5abe034).

It is caused by these two lines in netteForms.js:

```
	} else if (elem.name && !elem.form.elements.namedItem(elem.name).tagName) { // multi element
		return Nette.getValue(elem.form.elements.namedItem(elem.name));
```

When I revert them to the pre-2.3 version, it works fine:

```
	} else if (elem.form.elements[elem.name] && !elem.form.elements[elem.name].nodeName) { // multi element
		return Nette.getValue(elem.form.elements[elem.name]);
```

But I am not 100% sure this is the right solution because I don't know what was the reasoning behind using `namedItem` and `tagName` instead of `nodeName`.

You can test the sandbox in IE9 with a virtual machine [from here](https://www.modern.ie/en-us/virtualization-tools#downloads).

**Comment by Koricz** [comment]
Hi, I have the same problem in Internet Explorer 11.

Form is valid only when **first** radio is selected.

**Comment by dg** [comment]
DOM is really peace of **** :-( 

I really don't know how to retrieve list of radio inputs…

**Comment by ondrejmirtes** [comment]
Thank you, we will try this out as soon as possible.
