### ISSUE TITLE
CheckboxList rendering does not set label for and input id attributes

### ISSUE THREAD

**Issue by janlanger** [nette/forms#74]
When Checkboxlist is rendered via `{input listControl}` macro, the label tags do not have for attributes and inputs don't have ids.

When rendering by parts, eg. `{input listControl:1}` the ids and label-fors are added just fine.

**Comment by dg** [comment]
Yes.

**Comment by janlanger** [comment]
@dg I don't understand why this issue was closed. You consider this as "feature", proper behavior?

**Comment by dg** [comment]
They are simply not needed because inputs are inside labels.
