### ISSUE TITLE
Partial rendering of RadioList is very strict to default value

### ISSUE THREAD

**Issue by janedbal** [nette/forms#76]
This form definition

```php
$form->addRadioList('test', 'Test', [
    '1' => "one",
    '2' => "two",    
]);
$form->setDefaults(['test' => '1']);
```
with following rendering
```latte
{foreach ['1', '2'] as $key}
    {input test:$key}
    {label test:$key /}
{/foreach}
```

will not check the default radiolist value due to strict comparison [here](https://github.com/nette/forms/blob/8d9fe09520a64b2c58a70a3086b7372b89125d0d/src/Forms/Controls/RadioList.php#L141). Maybe the ```$key``` might be fixed by the same trick as used [here](https://github.com/nette/forms/blob/8d9fe09520a64b2c58a70a3086b7372b89125d0d/src/Forms/Controls/ChoiceControl.php#L65). What do you think?

-------

Example is quite artificial, but when the arrays are generated somewhere, it is not so obvious what is happening...

**Comment by dg** [comment]
Can you send PR or failing test?

**Comment by janedbal** [comment]
Sure.

**Comment by dg** [comment]
Thanks
