### ISSUE TITLE
macro <label n:name> does not print label value

### ISSUE THREAD

**Issue by Koricz** [nette/forms#83]
`$form->addText('field', 'My field');`

`//template`
`<form n:name="testForm">`
`    <label n:name="field"></label>	`
`    <input n:name="field">`
`</form>`

`//generated HTML code`
`<label for="frm-testForm-field"></label>`
`<input id="frm-testForm-field" type="text" name="field">`

Label is empty

**Comment by matej21** [comment]
that is a feature: 800df9beba71

you can use `<label n:name="field"/>` instead

**Comment by Koricz** [comment]
Ok and what is the reason of this BC break? A lot of templates to remake... ;-) :-(

Is the reason of this BC break to have the `for` html attribute generated and have blank caption?

If I want to have blank label I should set label to NULL in form...

**Comment by Koricz** [comment]
Is there any reason why this macro doesn't work with simple Checkbox? There is an inconsistency between macros.

`$form->addCheckbox('field', 'My field');`

`{input field} // input is rendered`
`{input field:} // input is rendered`
`{label field: /} // label is rendered`
`{label field /} //label is not rendered`

`<input n:name="field"> // input is rendered`
`<input n:name="field:"> // input is rendered`

`<label n:name="field" /> //Fatal error`
`<label n:name="field:" /> //Fatal error`

There should be an option to write template in same / common syntax, which is now impossible.

There are only two working combination now:

`{input field[:]} {label field: /}`

`<input n:name="field[:]"> {label field: /}`

**Comment by Koricz** [comment]
Possible new macro rendering proposal https://github.com/nette/forms/pull/84#issuecomment-109617985

**Comment by dg** [comment]
Fixed c2805efb1f7561e576df08f1ea3dceb800a00483
