### ISSUE TITLE
Default form rendering fails if source file is not in UTF8 encoding and uses rule with non-ascii message

### ISSUE THREAD

**Issue by janedbal** [nette/forms#88]
When rendering form with following rule and the source file is saved in Windows-1250, it results to ```Fatal Error: Method Nette\Utils\Html::__toString() must not throw an exception```. That's because ```Json::encode``` fails on exception ```Invalid UTF-8 sequence```.

```php
$form->addUpload('test', 'Test')
     ->addRule(Form::MAX_FILE_SIZE, 'Maximální velikost souboru je 1 MB', 1024);
```

I know it is probably expected to have all files in UTF8, but I have not found it in docs and therefore this might still be issue for beginners.

**Comment by dg** [comment]
So please send PR to documentation.

**Comment by janedbal** [comment]
Ok, can you point me to section where whould you like to have it?

**Comment by dg** [comment]
After ` jejíž volitelný argument je text chybové hlášky, která se zobrazí, pokud uživatel jméno nevyplní:`
