### ISSUE TITLE
Usage of rule Form::MAX_POST_SIZE leads to MemberAccessException

### ISSUE THREAD

**Issue by janedbal** [nette/forms#89]
Following rule leads to ```Nette\MemberAccessException: Call to undefined static method Nette\Forms\Validator::validatemaxPostSize().```.

```php
$form->addUpload('test', 'Test')
     ->addRule(Form::MAX_POST_SIZE, NULL, 1024);
```

Related: #30

**Comment by dg** [comment]
Use MAX_FILE_SIZE

**Comment by janedbal** [comment]
So there is currently (due to #30) no way to check uploaded size of all files? Form::MAX_FILE_SIZE checks size per-file, but when I use multiple upload, I cannot check total size by any rule?

**Comment by dg** [comment]
Unfortunately no, you can check maximal count of files and maximal size of file.
