### ISSUE TITLE
Continue loop - Minification problem

### ISSUE THREAD

**Issue by thaeriac** [nette/forms#98]
I know it is mainly my problem, but please can you replace [this label reference](https://github.com/nette/forms/blob/master/src/assets/netteForms.js#L308) with something else?
I am using jsshrink minification created by Jakub Vrána but his code is not possible to make it with this code. It does not know what to do with that part of code and shrink it in bad way => unfunction code.

Or, do you know ho to fix that on my side?

Thx :)

**Comment by dg** [comment]
Use Google Closure Compiler.
